### ISSUE TITLE
转码后的字符串复制时产生的问题

### ISSUE THREAD

**Issue by hongjie19970525** [inottn/img2base64#1]
转码后的字符串复制到其他地方，比如浏览器或者记事本上，都非常卡，不知道是啥原因

**Comment by inottn** [comment]
你好，根据你的描述，我无法判断问题出现的原因，希望能给出更具体的描述，如：
1. 系统版本
2. 浏览器版本
3. 上传图片大小

如果你上传的图片很大，也可能是如下原因：
Base64不是压缩算法，编码后反而会使数据变大约33%。编码的目的不是减小其大小，而是减少浏览器对图片发送Http请求的开销。如果图片很大，编码后文本也会很大。卡顿可能是记事本本身对文本读取的优化原因。
